name: Build iOS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # コードのチェックアウト
      - name: Checkout code
        uses: actions/checkout@v2

      # Flutterのセットアップ
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # CocoaPodsのインストール（必要に応じて）
      - name: Install CocoaPods
        run: sudo gem install cocoapods

      # プロジェクトのルートディレクトリに移動
      - name: Navigate to project root
        run: cd ${{ github.workspace }}

      # 依存関係のインストール
      - name: Install dependencies
        run: flutter pub get

      # iOSビルドの実行
      - name: Build iOS
        run: flutter build ios --release
