name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flutter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.5'

    - name: Install dependencies
      run: |
        cd ${{ github.workspace }}C:\Users\subar\uranai_app\.github\workflows # プロジェクトルートに移動
        flutter pub get

    - name: Run tests
      run: |
        flutter test
